<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA8cTHC5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA8cTHC5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA8cTHC5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA8cTHC5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA8cTHC5\App_KernelDevDebugContainer([
    'container.build_hash' => 'A8cTHC5',
    'container.build_id' => 'c4773ab8',
    'container.build_time' => 1648130482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA8cTHC5');
